package com.myspace.corporatelos.prescreening;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrescreeningScripts implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public PrescreeningScripts() {
	}

	public static void checkEntityBasics(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject partyResp = new org.json.JSONObject(kcontext
					.getVariable("partyResponse").toString());
			System.out.println("party Resp: " + partyResp);
			if (!partyResp.isNull("firstName")) {
				kcontext.setVariable("nameCheck", true);
			} else {
				kcontext.setVariable("nameCheck", false);
			}
			org.json.JSONArray partyArray = partyResp.getJSONArray("addresses");
			for (int i = 0; i < partyArray.length(); i++) {
				org.json.JSONObject indEle = new org.json.JSONObject(partyArray
						.get(i).toString());
				System.out.println("Addresses *****" + indEle.toString());
				if (!indEle.isNull("phoneNo")) {
					kcontext.setVariable("addressCheck", true);
					break;
				} else {
					kcontext.setVariable("addressCheck", false);
				}
			}

			org.json.JSONObject relationResp = new org.json.JSONObject(kcontext
					.getVariable("contactResponse").toString());
			System.out.println("Relations: ****" + relationResp.toString());
			org.json.JSONArray relationsArray = relationResp
					.getJSONArray("partyRelations");
			for (int i = 0; i < relationsArray.length(); i++) {
				org.json.JSONObject indEle = new org.json.JSONObject(
						relationsArray.get(i).toString());
				System.out.println("ind relation: " + indEle.toString());
				if (indEle.get("relationType").equals("Legal")) {
					kcontext.setVariable("relationCheck", true);
					break;
				} else {
					kcontext.setVariable("relationCheck", false);
				}
			}
			Boolean address = (Boolean) kcontext.getVariable("addressCheck");
			Boolean name = (Boolean) kcontext.getVariable("nameCheck");
			Boolean relation = (Boolean) kcontext.getVariable("relationCheck");
			System.out.println(name + " " + address + " " + relation);
			if (address && name && relation) {
				kcontext.setVariable("result", true);
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkEntityStatus(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			System.out.println("response: "
					+ kcontext.getVariable("response").toString());
			org.json.JSONObject responseObj = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			if (!responseObj.get("partyStatus").equals("Watchlist")) {
				kcontext.setVariable("result", true);
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkAddressInfo(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject addressResp = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			org.json.JSONArray addressArray = addressResp
					.getJSONArray("addresses");
			for (int i = 0; i < addressArray.length(); i++) {
				org.json.JSONObject indEle = new org.json.JSONObject(
						addressArray.get(i).toString());
				kcontext.setVariable("addressTypeCheck",
						(Boolean) indEle.get("primary"));
				System.out.println("primary flag: "
						+ kcontext.getVariable("addressTypeCheck"));
				if (!indEle.isNull("countryCode")
						&& !indEle.isNull("postalOrZipCode")) {
					kcontext.setVariable("addressInfoCheck", true);
					break;
				} else {
					kcontext.setVariable("addressInfoCheck", false);
				}
			}
			Boolean infoCheck = (Boolean) kcontext
					.getVariable("addressInfoCheck");
			Boolean typeCheck = (Boolean) kcontext
					.getVariable("addressTypeCheck");
			if (infoCheck && typeCheck) {
				kcontext.setVariable("result", true);
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkPartyRelation(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject relationResp = new org.json.JSONObject(kcontext
					.getVariable("partyRelationsResponse").toString());
			org.json.JSONArray relationsArray = relationResp
					.getJSONArray("partyRelations");
			if (relationsArray.length() > 0) {
				for (int i = 0; i < relationsArray.length(); i++) {
					org.json.JSONObject indEle = new org.json.JSONObject(
							relationsArray.get(i).toString());
					if (indEle.get("relationType").equals("Legal")) {
						kcontext.setVariable("relationCheck", true);
						break;
					} else {
						kcontext.setVariable("relationCheck", false);
					}
				}
			} else {
				kcontext.setVariable("relationCheck", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkContactReferences(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject partyResp = new org.json.JSONObject(kcontext
					.getVariable("partyResponse").toString());
			System.out.println("party Resp: " + partyResp);
			org.json.JSONArray contactArray = partyResp
					.getJSONArray("contactReferences");
			if (contactArray.length() > 0) {
				for (int i = 0; i < contactArray.length(); i++) {
					System.out.println("Contact Resp: "
							+ contactArray.get(i).toString());
					org.json.JSONObject indContact = new org.json.JSONObject(
							contactArray.get(i).toString());
					if (indContact.get("contactTypePurpose").equals("Primary")
							&& !indContact.isNull("jobTitle")) {
						kcontext.setVariable("contactCheck", true);
						System.out.println(indContact.get("contactPartyRef")
								.toString());
						kcontext.setVariable("contactPartyRef",
								indContact.get("contactPartyRef").toString());
						break;
					} else {
						kcontext.setVariable("contactCheck", false);
					}
				}
			} else {
				kcontext.setVariable("contactCheck", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkContactInfo(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject partyResp = new org.json.JSONObject(kcontext
					.getVariable("partyResponse").toString());
			System.out.println("party Resp: " + partyResp);
			if (!partyResp.isNull("firstName") && !partyResp.isNull("lastName")) {
				kcontext.setVariable("nameCheck", true);
			} else {
				kcontext.setVariable("nameCheck", false);
			}
			org.json.JSONArray partyArray = partyResp.getJSONArray("addresses");
			if (partyArray.length() > 0) {
				for (int i = 0; i < partyArray.length(); i++) {
					org.json.JSONObject indEle = new org.json.JSONObject(
							partyArray.get(i).toString());
					if (!indEle.isNull("phoneNo")) {
						kcontext.setVariable("phoneCheck", true);
						break;
					} else {
						kcontext.setVariable("phoneCheck", false);
					}
				}

				for (int i = 0; i < partyArray.length(); i++) {
					org.json.JSONObject indEle = new org.json.JSONObject(
							partyArray.get(i).toString());
					if (!indEle.isNull("electronicAddress")) {
						kcontext.setVariable("emailCheck", true);
						break;
					} else {
						kcontext.setVariable("emailCheck", false);
					}
				}
			} else {
				kcontext.setVariable("phoneCheck", false);
				kcontext.setVariable("emailCheck", false);
			}
			Boolean name = (Boolean) kcontext.getVariable("nameCheck");
			Boolean phone = (Boolean) kcontext.getVariable("phoneCheck");
			Boolean email = (Boolean) kcontext.getVariable("emailCheck");

			if (name && email && phone) {
				kcontext.setVariable("result", true);
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkFacilityStructure(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject facilitiesObj = new org.json.JSONObject(
					kcontext.getVariable("response").toString());//
			if (!facilitiesObj.isNull("totalAmount")
					&& (!facilitiesObj.isNull("year")
							|| !facilitiesObj.isNull("month") || !facilitiesObj
								.isNull("days"))) {
				kcontext.setVariable("result", true);
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkFacilityPricing(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject responseObj = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			org.json.JSONArray pricingArr = responseObj.getJSONArray("pricing");
			if (pricingArr.length() > 0) {
				for (int i = 0; i < pricingArr.length(); i++) {
					org.json.JSONObject indPricingEle = new org.json.JSONObject(
							pricingArr.get(i).toString());
					if (indPricingEle.get("interestRateType").equals("01")) {
						org.json.JSONObject fixEle = new org.json.JSONObject(
								indPricingEle.get("fixedInterestRate")
										.toString());
						if (!fixEle.isNull("interestSpread")
								&& !fixEle.isNull("indicativeBaseRate")
								&& !fixEle.isNull("paymentFrequency")
								&& !fixEle.isNull("period")) {
							kcontext.setVariable("result", true);
						}
					} else if (indPricingEle.get("interestRateType").equals(
							"02")) {
						org.json.JSONObject periodEle = new org.json.JSONObject(
								indPricingEle.get("periodicInterestRate")
										.toString());
						if (!periodEle.isNull("interestSpread")
								&& !periodEle.isNull("indicativeBaseRate")
								&& !periodEle.isNull("paymentFrequency")
								&& !periodEle.isNull("period")) {
							kcontext.setVariable("result", true);
						}

					} else if (indPricingEle.get("interestRateType").equals(
							"03")) {
						org.json.JSONObject floatingEle = new org.json.JSONObject(
								indPricingEle.get("floatingInterestRate")
										.toString());
						if (!floatingEle.isNull("interestSpread")
								&& !floatingEle.isNull("indicativeBaseRate")
								&& !floatingEle.isNull("paymentFrequency")
								&& !floatingEle.isNull("period")) {
							kcontext.setVariable("result", true);
						}
					}
				}
			} else {
				kcontext.setVariable("result", false);

			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkBusinessBasics(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject partyResp = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			if (!partyResp.isNull("dateOfIncorporation")) {
				kcontext.setVariable("orgCheck", true);
			} else {
				kcontext.setVariable("orgCheck", false);
			}
			org.json.JSONArray identifierArray = partyResp
					.getJSONArray("partyIdentifiers");
			for (int i = 0; i < identifierArray.length(); i++) {
				org.json.JSONObject identifierEle = new org.json.JSONObject(
						identifierArray.get(i).toString());
				if (identifierEle.get("type").equals("Registration")
						&& !identifierEle.isNull("identifierNumber")) {
					kcontext.setVariable("identifierCheck", true);
					break;
				} else {
					kcontext.setVariable("identifierCheck", false);
				}
			}
			Boolean org = (Boolean) kcontext.getVariable("orgCheck");
			Boolean identifier = (Boolean) kcontext
					.getVariable("identifierCheck");
			if (org && identifier) {
				kcontext.setVariable("result", true);
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkBeneOwner(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject relationsResp = new org.json.JSONObject(
					kcontext.getVariable("response").toString());
			org.json.JSONArray relationsArr = relationsResp
					.getJSONArray("partyRelations");
			for (int i = 0; i < relationsArr.length(); i++) {
				org.json.JSONObject indRelation = new org.json.JSONObject(
						relationsArr.get(i).toString());
				if (!indRelation.isNull("ownershipPercentage")
						&& java.lang.Integer.parseInt(indRelation.get(
								"ownershipPercentage").toString()) >= 25) {
					kcontext.setVariable("result", true);
					break;
				} else {
					kcontext.setVariable("result", false);
				}
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkCompanyInfo(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject partyResp = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			if (!partyResp.isNull("dateOfIncorporation")) {
				String dateOfIncorporation = partyResp.get(
						"dateOfIncorporation").toString();
				java.time.LocalDate companyDate = java.time.LocalDate
						.parse(dateOfIncorporation);
				System.out.println("Company Date: " + companyDate.toString());
				java.time.Period difference = java.time.Period.between(
						companyDate, java.time.LocalDate.now());
				if (difference.getYears() > 2) {
					kcontext.setVariable("result", true);
				} else {
					kcontext.setVariable("result", false);
				}
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkAnnualStatement(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject responseJSON = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			if (responseJSON.has("documentsList")) {
				org.json.JSONArray documentsArray = responseJSON
						.getJSONArray("documentsList");
				if (documentsArray.length() > 0) {
					for (int i = 0; i < documentsArray.length(); i++) {
						org.json.JSONObject indDocument = new org.json.JSONObject(
								documentsArray.get(i).toString());
						if (indDocument.get("documentType").equals("08")) {
							kcontext.setVariable("result", true);
							break;
						} else {
							kcontext.setVariable("result", false);
						}
					}
				} else {
					kcontext.setVariable("result", false);
				}
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkBusinessEvidence(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject responseJSON = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			if (responseJSON.has("documentsList")) {
				org.json.JSONArray documentsArray = responseJSON
						.getJSONArray("documentsList");
				if (documentsArray.length() > 0) {
					for (int i = 0; i < documentsArray.length(); i++) {
						org.json.JSONObject indDocument = new org.json.JSONObject(
								documentsArray.get(i).toString());
						if (indDocument.get("documentType").equals("11")) {
							kcontext.setVariable("result", true);
							break;
						} else {
							kcontext.setVariable("result", false);
						}
					}
				} else {
					kcontext.setVariable("result", false);
				}
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}
}