package com.temenos.infinityassist.sme;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SMEScripts implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public SMEScripts() {
	}

	public static void setRequestId(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			String response = (String) kcontext.getVariable("response");
			org.json.JSONObject responseJSON = new org.json.JSONObject(response);
			kcontext.setVariable("requestId",
					responseJSON.getString("requestId"));
		} catch (Exception e) {

		}
	}

	public static void setCompanyIds(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			String response = (String) kcontext.getVariable("response");
			org.json.JSONObject responseJSON = new org.json.JSONObject(response);
			kcontext.setVariable("companyCifId",
					responseJSON.getString("coreCustomerId"));
			kcontext.setVariable("companyPartyId",
					responseJSON.getString("partyID"));
		} catch (Exception e) {

		}
	}

	public static void checkSignedOfferLetter(
			org.kie.api.runtime.process.ProcessContext kcontext,
			String documentResponse) {
		try {
			org.json.JSONObject documents = new org.json.JSONObject(
					documentResponse);
			org.json.JSONArray documentsArray = documents
					.getJSONArray("documents");
			if (documentsArray.length() > 0) {
				for (int index = 0; index < documentsArray.length(); index++) {
					org.json.JSONObject doc = documentsArray
							.getJSONObject(index);
					if (doc.get("documentType").toString().equals("35")
							&& doc.get("documentStatus").toString()
									.equals("05")) {
						kcontext.setVariable("isSigned", true);
						break;
					} else {
						kcontext.setVariable("isSigned", false);
					}
				}
			} else {
				kcontext.setVariable("isSigned", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void checkApprovedOfferLetter(
			org.kie.api.runtime.process.ProcessContext kcontext,
			String documentResponse) {
		try {
			org.json.JSONObject documents = new org.json.JSONObject(
					documentResponse);
			org.json.JSONArray documentsArray = documents
					.getJSONArray("documents");
			if (documentsArray.length() > 0) {
				for (int index = 0; index < documentsArray.length(); index++) {
					org.json.JSONObject doc = documentsArray
							.getJSONObject(index);
					if (doc.get("documentType").toString().equals("35")
							&& doc.get("documentStatus").toString()
									.equals("01")) {
						kcontext.setVariable("isApproved", true);
						break;
					} else {
						kcontext.setVariable("isApproved", false);
					}
				}
			} else {
				kcontext.setVariable("isApproved", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void setParties(
			org.kie.api.runtime.process.ProcessContext kcontext,
			String relatedPartiesResponse) {
		try {
			org.json.JSONObject relatedParties = new org.json.JSONObject(
					relatedPartiesResponse);
			org.json.JSONArray relatedPartiesArray = relatedParties
					.getJSONArray("relatedParties");
			java.util.Set<String> prospectParties = new java.util.HashSet<>();
			java.util.Set<String> existingParties = new java.util.HashSet<>();
			java.util.Map<String, String> partyMap = new java.util.HashMap<>();
			for (int index = 0; index < relatedPartiesArray.length(); index++) {
				org.json.JSONObject party = relatedPartiesArray
						.getJSONObject(index);
				String partyId = party.getString("relatedPartyId");
				String role = party.getString("relatedPartyRole");
				partyMap.put(partyId, role);
				if (partyId.startsWith("NNVF") && !role.equals("01")) {
					prospectParties.add(partyId);
				} else if (partyId.startsWith("ENVF") && !role.equals("01")) {
					existingParties.add(partyId);
				}
			}
			kcontext.setVariable("partyRoleMap", partyMap);
			kcontext.setVariable("prospectParties", prospectParties);
			kcontext.setVariable("existingParties", existingParties);
		} catch (Exception e) {

		}
	}

	public static void getFacilities(
			org.kie.api.runtime.process.ProcessContext kcontext,
			String facilitiesResponse) {
		try {
			org.json.JSONObject facilities = new org.json.JSONObject(
					facilitiesResponse);
			org.json.JSONArray facilitiesArray = facilities
					.getJSONArray("facilities");
			java.util.List<String> facilityList = new java.util.ArrayList<String>();
			for (int index = 0; index < facilitiesArray.length(); index++) {
				org.json.JSONObject facility = facilitiesArray
						.getJSONObject(index);
				if (facility.get("approvalStatusId").toString().equals("03")) {
					facilityList.add(facility.get("facilityId").toString());
				}
			}
			kcontext.setVariable("facilitiesList", facilityList);
		} catch (Exception e) {

		}
	}

	public static void setTransactionId(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			String response = (String) kcontext.getVariable("response");
			org.json.JSONObject responseJSON = new org.json.JSONObject(response);
			kcontext.setVariable("transactionId",
					responseJSON.getString("transactionId"));
		} catch (Exception e) {

		}
	}

	public static void checkCreditDecision(
			org.kie.api.runtime.process.ProcessContext kcontext,
			String decisionResponse) {
		try {
			org.json.JSONObject creditDecisions = new org.json.JSONObject(
					decisionResponse);
			if (creditDecisions.has("decisions")) {
				org.json.JSONArray decisionsArray = creditDecisions
						.getJSONArray("decisions");
				String facilityId = kcontext.getVariable("facilityId")
						.toString();
				for (int index = 0; index < decisionsArray.length(); index++) {
					org.json.JSONObject decision = decisionsArray
							.getJSONObject(index);
					if (decision.get("facilityId").toString()
							.equals(facilityId)
							&& decision.get("finalDecision").toString()
									.equals("true")
							&& (decision.get("decisionId").toString()
									.equals("02") || decision.get("decisionId")
									.toString().equals("03"))) {
						kcontext.setVariable("hasDecision", true);
						if (decision.get("decisionId").toString().equals("02")) {
							kcontext.setVariable("approvalStatusId", "01");
						} else if (decision.get("decisionId").toString()
								.equals("03")) {
							kcontext.setVariable("approvalStatusId", "02");
						}
						break;
					} else {
						kcontext.setVariable("hasDecision", false);
					}
				}
			} else {
				kcontext.setVariable("hasDecision", false);
			}
		} catch (Exception e) {

		}
	}

}
